-- Create "bootstrap_states" table
CREATE TABLE "bootstrap_states" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "singleton_key" bigint NOT NULL DEFAULT 1, "initialized_at" timestamptz NOT NULL, "admin_user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "ck_bootstrap_state_singleton" CHECK (singleton_key = 1));
-- Create index "uq_bootstrap_state_singleton" to table: "bootstrap_states"
CREATE UNIQUE INDEX "uq_bootstrap_state_singleton" ON "bootstrap_states" ("singleton_key");
-- Create "dynamic_settings" table
CREATE TABLE "dynamic_settings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "key" text NOT NULL, "type" text NOT NULL, "value" json NOT NULL, "updated_by" bigint NOT NULL, "updated_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "ck_dynamic_settings_type" CHECK (type = ANY (ARRAY['string'::text, 'integer'::text, 'boolean'::text, 'json'::text])));
-- Create index "uq_dynamic_settings_key" to table: "dynamic_settings"
CREATE UNIQUE INDEX "uq_dynamic_settings_key" ON "dynamic_settings" ("key");
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "email" text NOT NULL, "email_normalized" text NOT NULL, "nickname" text NOT NULL, "website_url" text NULL, "role" text NOT NULL DEFAULT 'user', "status" text NOT NULL DEFAULT 'active', "password_hash" text NULL, "password_changed_at" timestamptz NULL, "session_version" bigint NOT NULL DEFAULT 1, "email_verified_at" timestamptz NULL, "deleted_at" timestamptz NULL, "status_before_delete" text NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "ck_users_password_state" CHECK (((password_hash IS NULL) AND (password_changed_at IS NULL)) OR ((password_hash IS NOT NULL) AND (password_changed_at IS NOT NULL))), CONSTRAINT "ck_users_role" CHECK (role = ANY (ARRAY['admin'::text, 'user'::text])), CONSTRAINT "ck_users_session_version" CHECK (session_version > 0), CONSTRAINT "ck_users_status" CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text, 'deleted'::text])));
-- Create index "uq_users_email_normalized" to table: "users"
CREATE UNIQUE INDEX "uq_users_email_normalized" ON "users" ("email_normalized");
-- Create "sites" table
CREATE TABLE "sites" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" text NOT NULL, "canonical_url" text NOT NULL, "status" text NOT NULL DEFAULT 'active', "created_at" timestamptz NULL, "updated_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "ck_sites_status" CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text])));
-- Create "threads" table
CREATE TABLE "threads" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "site_id" bigint NOT NULL, "page_key" text NOT NULL, "page_url" text NULL, "page_title" text NULL, "comments_enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_threads_site" FOREIGN KEY ("site_id") REFERENCES "sites" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create index "uq_threads_site_id" to table: "threads"
CREATE UNIQUE INDEX "uq_threads_site_id" ON "threads" ("site_id", "id");
-- Create index "uq_threads_site_page" to table: "threads"
CREATE UNIQUE INDEX "uq_threads_site_page" ON "threads" ("site_id", "page_key");
-- Create "comments" table
CREATE TABLE "comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "site_id" bigint NOT NULL, "thread_id" bigint NOT NULL, "user_id" bigint NOT NULL, "parent_id" bigint NULL, "root_id" bigint NULL, "reply_to_user_id" bigint NULL, "depth" bigint NOT NULL DEFAULT 0, "body_markdown" text NOT NULL, "status" text NOT NULL DEFAULT 'pending', "status_before_delete" text NULL, "ip_mode" text NOT NULL DEFAULT 'none', "ip_value" text NULL, "ua_mode" text NOT NULL DEFAULT 'none', "ua_raw" text NULL, "ua_browser" text NULL, "ua_os" text NULL, "ua_device" text NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "published_at" timestamptz NULL, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_comments_reply_to_user" FOREIGN KEY ("reply_to_user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE SET NULL, CONSTRAINT "fk_comments_site" FOREIGN KEY ("site_id") REFERENCES "sites" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "fk_comments_thread" FOREIGN KEY ("site_id", "thread_id") REFERENCES "threads" ("site_id", "id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "fk_comments_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "ck_comments_depth" CHECK (depth >= 0), CONSTRAINT "ck_comments_ip_mode" CHECK (ip_mode = ANY (ARRAY['none'::text, 'coarse'::text, 'full'::text])), CONSTRAINT "ck_comments_status" CHECK (status = ANY (ARRAY['pending'::text, 'published'::text, 'spam'::text, 'deleted'::text])), CONSTRAINT "ck_comments_ua_mode" CHECK (ua_mode = ANY (ARRAY['none'::text, 'coarse'::text, 'full'::text])));
-- Create index "idx_comments_public" to table: "comments"
CREATE INDEX "idx_comments_public" ON "comments" ("site_id", "thread_id", "created_at", "id");
-- Create index "idx_comments_reply_to" to table: "comments"
CREATE INDEX "idx_comments_reply_to" ON "comments" ("reply_to_user_id");
-- Create index "idx_comments_site_parent" to table: "comments"
CREATE INDEX "idx_comments_site_parent" ON "comments" ("site_id", "parent_id", "created_at", "id");
-- Create index "idx_comments_site_root" to table: "comments"
CREATE INDEX "idx_comments_site_root" ON "comments" ("site_id", "root_id", "created_at", "id");
-- Create index "idx_comments_site_status" to table: "comments"
CREATE INDEX "idx_comments_site_status" ON "comments" ("site_id", "status", "created_at", "id");
-- Create index "idx_comments_user" to table: "comments"
CREATE INDEX "idx_comments_user" ON "comments" ("user_id", "created_at", "id");
-- Create index "uq_comments_site_id" to table: "comments"
CREATE UNIQUE INDEX "uq_comments_site_id" ON "comments" ("site_id", "id");
-- Add self-referencing comment foreign keys after the referenced unique index exists
ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_parent" FOREIGN KEY ("site_id", "parent_id") REFERENCES "comments" ("site_id", "id") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_root" FOREIGN KEY ("site_id", "root_id") REFERENCES "comments" ("site_id", "id") ON UPDATE CASCADE ON DELETE CASCADE;
-- Create "external_identities" table
CREATE TABLE "external_identities" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "provider_key" text NOT NULL, "provider_subject" text NOT NULL, "verified_email" text NOT NULL, "created_at" timestamptz NULL, "last_login_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_external_identities_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create index "uq_external_identities_provider_subject" to table: "external_identities"
CREATE UNIQUE INDEX "uq_external_identities_provider_subject" ON "external_identities" ("provider_key", "provider_subject");
-- Create index "uq_external_identities_user_provider" to table: "external_identities"
CREATE UNIQUE INDEX "uq_external_identities_user_provider" ON "external_identities" ("user_id", "provider_key", "provider_subject");
-- Create "notification_preferences" table
CREATE TABLE "notification_preferences" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "reply_enabled" boolean NOT NULL DEFAULT true, "moderation_enabled" boolean NOT NULL DEFAULT true, "updated_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_notification_preferences_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create index "uq_notification_preferences_user" to table: "notification_preferences"
CREATE UNIQUE INDEX "uq_notification_preferences_user" ON "notification_preferences" ("user_id");
-- Create "passkey_credentials" table
CREATE TABLE "passkey_credentials" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "credential_id" text NOT NULL, "public_key" bytea NOT NULL, "attestation_type" text NULL, "transports" text NULL, "sign_count" bigint NOT NULL DEFAULT 0, "backup_eligible" boolean NOT NULL DEFAULT false, "backup_state" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "created_at" timestamptz NULL, "last_used_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_passkey_credentials_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create index "uq_passkey_credentials_credential_id" to table: "passkey_credentials"
CREATE UNIQUE INDEX "uq_passkey_credentials_credential_id" ON "passkey_credentials" ("credential_id");
-- Create "site_origins" table
CREATE TABLE "site_origins" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "site_id" bigint NOT NULL, "origin" text NOT NULL, "created_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_site_origins_site" FOREIGN KEY ("site_id") REFERENCES "sites" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create index "uq_site_origins_site_origin" to table: "site_origins"
CREATE UNIQUE INDEX "uq_site_origins_site_origin" ON "site_origins" ("site_id", "origin");
